# Bayesian Hyperparameter Space Optimization and Automated Model Auditing Pipeline

In [1]:
%load_ext autoreload
%autoreload 2

import os
import mlflow
import optuna
from optuna.integration.mlflow import MLflowCallback
from optuna.pruners import MedianPruner
import numpy as np
import pandas as pd

from src import feature_engineering as fe
from src import optuna_optimization as utils
from src import mlflow_utils as mlf_utils

/Users/hector.vargas/repos/ml_hands_on_project/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Path Configuration & MLflow Backend Binding

In [2]:
RANDOM_STATE = 42
N_SPLITS = 5
EXPERIMENT_NAME = "customer-churn-optuna"

from pathlib import Path

def _find_project_root():
    """Find the project root by looking for pyproject.toml."""
    current = Path.cwd()
    for parent in [current] + list(current.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    raise FileNotFoundError("Could not find project root (pyproject.toml)")

ROOT_DIR = str(_find_project_root())
DB_PATH = os.path.join(ROOT_DIR, "mlflow.db")
ARTIFACTS_DIR = os.path.join(ROOT_DIR, "mlartifacts")

# Set the tracking URI immediately to lock it to SQLite
mlflow.set_tracking_uri(f"sqlite:///{DB_PATH}")

# Explicitly create the experiment with your designated mlartifacts folder path
experiment_id = mlf_utils.init_mlflow_experiment(
    EXPERIMENT_NAME,
    DB_PATH,
    ARTIFACTS_DIR,
)

# Active the experiment scope
mlflow.set_experiment(EXPERIMENT_NAME)

<Experiment: artifact_location='file:///Users/hector.vargas/repos/ml_hands_on_project/mlartifacts', creation_time=1781781840960, experiment_id='1', last_update_time=1781781840960, lifecycle_stage='active', name='customer-churn-optuna', tags={}, trace_location=None, workspace='default'>

## 2. Custom Source Code Ingestion

In [3]:
X_train = pd.read_csv("../data/processed/raw_features/X_train.csv")
X_test = pd.read_csv("../data/processed/raw_features/X_test.csv")
y_train = pd.read_csv("../data/processed/target/y_train.csv").squeeze()
y_test = pd.read_csv("../data/processed/target/y_test.csv").squeeze()

## 2. Orchestrate and Initialize Search Parameter Studies

In [4]:
selected_features = [
    # Binary
    "is_silver",
    "is_germany",
    "is_spain",
    "Num_Of_Products_1",
    "Num_Of_Products_2",
    "Num_Of_Products_3",
    "Num_Of_Products_4",

    # Continuous
    "Age_x_IsActive",
    "Balance_per_Product",
    "CreditScore_per_Age",
    "Inactive_x_Balance",
    "CreditScore_x_Age",
    "Products_per_Tenure",
]
# Schema Baseline Columns Definitions
nomod_columns = []
dummyfy_columns = ['Gender']
norm_std_columns = ['Point Earned', 'Satisfaction Score', 'EstimatedSalary']

# Initialize the Feature Engineer class with the desired subset strings
feature_engineer_object = fe.DynamicFeatureEngineer(selected_features=selected_features)
binary_features = feature_engineer_object._get_all_binary_features()
continuous_features = feature_engineer_object._get_all_continuous_features()

current_layout = {
    "passthrough": nomod_columns + binary_features,
    "standard_scale": norm_std_columns + continuous_features,
    "one_hot_encode": dummyfy_columns
}

EXPERIMENT_REGISTRY = {
    "experiment_1": current_layout
}

# Initialize Integrated MLflow Tracking Integration Callbacks
mlflow_callback = MLflowCallback(
    tracking_uri=mlflow.get_tracking_uri(),
    metric_name="pr_auc",
    create_experiment=False,
    mlflow_kwargs={
        "nested": True,
        "experiment_id": experiment_id,
    },
)

study = optuna.create_study(
    study_name="customer-churn-rf-search-v1",
    direction="maximize",
    pruner=MedianPruner(n_startup_trials=5, n_warmup_steps=0),
    sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE),
)

# FIXED: Removed the invalid FULL_REGISTRY argument variable completely
# Instantiate the objective function with both training and testing datasets
objective_function = utils.ObjectiveCV(
    X=X_train,
    y=y_train,
    current_layout=current_layout,
    n_splits=N_SPLITS,
    random_state=RANDOM_STATE,
)

/var/folders/bv/50x24wc545x5mclk_t88ryrc0000gn/T/ipykernel_19579/580893370.py:40: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
[I 2026-06-18 05:51:05,184] A new study created in memory with name: customer-churn-rf-search-v1

## 3. Run Optimization Search Workspace Execution Window

In [ ]:
# Execute the parent run context block
with mlflow.start_run(
    run_name="optuna_search_parent",
    experiment_id=experiment_id,
):    
    study.optimize(
        objective_function,
        n_trials=5000,
        callbacks=[mlflow_callback]
    )

    # Log global baseline metrics directly to the parent run metadata shell
    mlflow.log_metric("best_auc", study.best_value)
    mlflow.log_params(study.best_params)

    # Reconstruct the pipeline architecture using the best parameters found
    best_pipeline = utils.build_pipeline(
        trial=study.best_trial, 
        current_layout=current_layout,
        random_state=RANDOM_STATE
    )

    # Run full evaluations and save serialization schema artifacts to the parent run
    utils.evaluate_and_log_best_model(
        best_pipeline=best_pipeline,
        X_train=X_train, 
        y_train=y_train,
        X_test=X_test, 
        y_test=y_test,
        current_layout=current_layout,
    )

[I 2026-06-18 05:51:08,381] Trial 0 finished with value: 0.6788379596098221 and parameters: {'scaler': 'minmax', 'encoder': 'drop_first', 'model': 'rf', 'rf_n_estimators': 293, 'rf_max_depth': 12, 'rf_min_samples_split': 25, 'rf_min_samples_leaf': 1}. Best is trial 0 with value: 0.6788379596098221.
[I 2026-06-18 05:51:09,934] Trial 1 finished with value: 0.6953347996684984 and parameters: {'scaler': 'std', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1059, 'xgb_learning_rate': 0.029667626364545993, 'xgb_subsample': 0.9644741157888952, 'xgb_colsample_bytree': 0.47092407909780626, 'xgb_gamma': 2.0842892970704363, 'xgb_reg_alpha': 6.78905327169848e-07, 'xgb_reg_lambda': 1.9069966103000426e-07, 'xgb_scale_pos_weight': 1.992587980696507}. Best is trial 1 with value: 0.6953347996684984.
[I 2026-06-18 05:51:12,115] Trial 2 finished with value: 0.6800919420716183 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'rf', 'rf_n_estimators': 295, 'rf_max_depth': 13, 'rf_min_samples_split': 26, 'rf_min_samples_leaf': 1}. Best is trial 1 with value: 0.6953347996684984.
[I 2026-06-18 05:51:13,572] Trial 3 finished with value: 0.6905380055052728 and parameters: {'scaler': 'minmax', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 955, 'xgb_learning_rate': 0.03690317493012618, 'xgb_subsample': 0.9524684430435764, 'xgb_colsample_bytree': 0.5280102031766716, 'xgb_gamma': 2.5934205586865593, 'xgb_reg_alpha': 8.399864445957488e-08, 'xgb_reg_lambda': 7.045683638454505e-05, 'xgb_scale_pos_weight': 1.9875664116805574}. Best is trial 1 with value: 0.6953347996684984.
[I 2026-06-18 05:51:14,593] Trial 4 finished with value: 0.6760561038589349 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'rf', 'rf_n_estimators': 285, 'rf_max_depth': 10, 'rf_min_samples_split': 20, 'rf_min_samples_leaf': 3}. Best is trial 1 with value: 0.6953347996684984.
[I 2026-06-18 05:51:14,981] Trial 5 finished with value: 0.696080382965133 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1264, 'xgb_learning_rate': 0.02809743391955222, 'xgb_subsample': 0.940220884684944, 'xgb_colsample_bytree': 0.5723192142682251, 'xgb_gamma': 2.9137146876952342, 'xgb_reg_alpha': 4.416068895118589e-05, 'xgb_reg_lambda': 7.183758655813991e-06, 'xgb_scale_pos_weight': 1.6370223258670453}. Best is trial 5 with value: 0.696080382965133.
[I 2026-06-18 05:51:15,285] Trial 6 finished with value: 0.6930267315278726 and parameters: {'scaler': 'robust', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 995, 'xgb_learning_rate': 0.03838737414135848, 'xgb_subsample': 0.9655022988542085, 'xgb_colsample_bytree': 0.5830819113864489, 'xgb_gamma': 2.444429850323899, 'xgb_reg_alpha': 3.962517832572335e-08, 'xgb_reg_lambda': 3.683188416535899e-06, 'xgb_scale_pos_weight': 1.9803925243084488}. Best is trial 5 with value: 0.696080382965133.
[I 2026-06-18 05:51:15,542] Trial 7 finished with value: 0.6950854118514185 and parameters: {'scaler': 'minmax', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 818, 'xgb_learning_rate': 0.03634110166546641, 'xgb_subsample': 0.9525742392430531, 'xgb_colsample_bytree': 0.5262856036747054, 'xgb_gamma': 3.3151329478521863, 'xgb_reg_alpha': 1.763847954354684e-07, 'xgb_reg_lambda': 1.1269758643814665e-07, 'xgb_scale_pos_weight': 1.9777755692715244}. Best is trial 5 with value: 0.696080382965133.
[I 2026-06-18 05:51:16,567] Trial 8 pruned.
[I 2026-06-18 05:51:16,916] Trial 9 pruned.
[I 2026-06-18 05:51:17,283] Trial 10 finished with value: 0.6948797138486265 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1367, 'xgb_learning_rate': 0.025252946927908033, 'xgb_subsample': 0.9763065918113006, 'xgb_colsample_bytree': 0.5954744698168214, 'xgb_gamma': 3.2412600465577097, 'xgb_reg_alpha': 0.00015512071780208642, 'xgb_reg_lambda': 9.158267559026631e-05, 'xgb_scale_pos_weight': 1.6135151059047093}. Best is trial 5 with value: 0.696080382965133.
[I 2026-06-18 05:51:17,684] Trial 11 pruned.
[I 2026-06-18 05:51:18,046] Trial 12 finished with value: 0.6930771262073894 and parameters: {'scaler': 'std', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1117, 'xgb_learning_rate': 0.02984616634280507, 'xgb_subsample': 0.9407330232239131, 'xgb_colsample_bytree': 0.46176935774501715, 'xgb_gamma': 1.946134776506206, 'xgb_reg_alpha': 6.635139581380295e-06, 'xgb_reg_lambda': 3.0040005222767815e-06, 'xgb_scale_pos_weight': 1.6127747474052716}. Best is trial 5 with value: 0.696080382965133.
[I 2026-06-18 05:51:18,371] Trial 13 finished with value: 0.697981567750783 and parameters: {'scaler': 'std', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1128, 'xgb_learning_rate': 0.030776978961164346, 'xgb_subsample': 0.957368745168243, 'xgb_colsample_bytree': 0.4899407498454361, 'xgb_gamma': 2.9361812703609886, 'xgb_reg_alpha': 0.00040937843061725047, 'xgb_reg_lambda': 1.5521646818767052e-08, 'xgb_scale_pos_weight': 2.0874037118791944}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:18,710] Trial 14 finished with value: 0.6937839478097628 and parameters: {'scaler': 'std', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1164, 'xgb_learning_rate': 0.03185946776663539, 'xgb_subsample': 0.9496193401169366, 'xgb_colsample_bytree': 0.5594284085431039, 'xgb_gamma': 2.8763522633589176, 'xgb_reg_alpha': 0.0009760974994746518, 'xgb_reg_lambda': 5.532106476073867e-09, 'xgb_scale_pos_weight': 1.846917639109328}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:19,063] Trial 15 finished with value: 0.6961402602058927 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1197, 'xgb_learning_rate': 0.025732785070959517, 'xgb_subsample': 0.9785701226117322, 'xgb_colsample_bytree': 0.4922121389368439, 'xgb_gamma': 2.934228638828272, 'xgb_reg_alpha': 7.122473742271299e-05, 'xgb_reg_lambda': 2.1450874736621476e-08, 'xgb_scale_pos_weight': 2.0782554715108303}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:19,413] Trial 16 finished with value: 0.6954084292364086 and parameters: {'scaler': 'std', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1177, 'xgb_learning_rate': 0.025539220003796926, 'xgb_subsample': 0.9791826457713972, 'xgb_colsample_bytree': 0.4926456686805427, 'xgb_gamma': 2.9251550836023723, 'xgb_reg_alpha': 0.0006625183599299567, 'xgb_reg_lambda': 2.339581869743125e-08, 'xgb_scale_pos_weight': 2.087988290980488}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:19,713] Trial 17 finished with value: 0.697119458067527 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1046, 'xgb_learning_rate': 0.03363611197986273, 'xgb_subsample': 0.9729852890208792, 'xgb_colsample_bytree': 0.4909987153245742, 'xgb_gamma': 3.4825543922871987, 'xgb_reg_alpha': 0.00011251116512621986, 'xgb_reg_lambda': 1.126404362417794e-09, 'xgb_scale_pos_weight': 2.0938014311659305}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:20,576] Trial 18 pruned.
[I 2026-06-18 05:51:20,854] Trial 19 finished with value: 0.6960676917209725 and parameters: {'scaler': 'minmax', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 916, 'xgb_learning_rate': 0.033540067241993154, 'xgb_subsample': 0.9587995933821248, 'xgb_colsample_bytree': 0.49601028200514985, 'xgb_gamma': 3.4364431552173254, 'xgb_reg_alpha': 0.00021664467462422415, 'xgb_reg_lambda': 1.1672564218636645e-09, 'xgb_scale_pos_weight': 2.057250785256552}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:21,156] Trial 20 finished with value: 0.696649876654029 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1058, 'xgb_learning_rate': 0.03250856808654554, 'xgb_subsample': 0.9714425613000947, 'xgb_colsample_bytree': 0.5038333904389889, 'xgb_gamma': 3.1633352566206656, 'xgb_reg_alpha': 2.123843428931308e-06, 'xgb_reg_lambda': 1.0962111993884218e-09, 'xgb_scale_pos_weight': 1.9129023532503981}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:21,463] Trial 21 finished with value: 0.6972124320817735 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1061, 'xgb_learning_rate': 0.0327644111135311, 'xgb_subsample': 0.9716074922327937, 'xgb_colsample_bytree': 0.506492900469435, 'xgb_gamma': 3.1296544810117704, 'xgb_reg_alpha': 1.4286962569445287e-06, 'xgb_reg_lambda': 1.3012833126331063e-09, 'xgb_scale_pos_weight': 1.9083278731152071}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:21,761] Trial 22 finished with value: 0.6965629031984633 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1039, 'xgb_learning_rate': 0.03532481387250369, 'xgb_subsample': 0.9712605726616985, 'xgb_colsample_bytree': 0.5103698950747797, 'xgb_gamma': 3.496745051024998, 'xgb_reg_alpha': 1.1119761223013236e-08, 'xgb_reg_lambda': 6.3726031701976796e-09, 'xgb_scale_pos_weight': 2.043584938345713}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:22,070] Trial 23 finished with value: 0.697693071462536 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1102, 'xgb_learning_rate': 0.03140421175004263, 'xgb_subsample': 0.9720737813340702, 'xgb_colsample_bytree': 0.47577184547906004, 'xgb_gamma': 3.1568678116408595, 'xgb_reg_alpha': 1.5035157438716053e-06, 'xgb_reg_lambda': 2.4071892604438602e-08, 'xgb_scale_pos_weight': 1.886611564121649}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:22,393] Trial 24 finished with value: 0.6975739458260719 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1116, 'xgb_learning_rate': 0.03097018708546587, 'xgb_subsample': 0.957954224879855, 'xgb_colsample_bytree': 0.47480800234927467, 'xgb_gamma': 2.695242106775213, 'xgb_reg_alpha': 1.5937945128601284e-06, 'xgb_reg_lambda': 4.013481796064713e-08, 'xgb_scale_pos_weight': 1.8981688564430372}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:22,723] Trial 25 pruned.
[I 2026-06-18 05:51:23,692] Trial 26 pruned.
[I 2026-06-18 05:51:24,042] Trial 27 finished with value: 0.6961869394269601 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1203, 'xgb_learning_rate': 0.027390616495667264, 'xgb_subsample': 0.9556777711398775, 'xgb_colsample_bytree': 0.4757810425816685, 'xgb_gamma': 2.723186984455671, 'xgb_reg_alpha': 6.393389655854054e-06, 'xgb_reg_lambda': 4.605307196538446e-08, 'xgb_scale_pos_weight': 1.7763010681878368}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:24,355] Trial 28 finished with value: 0.6964833957108438 and parameters: {'scaler': 'minmax', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1114, 'xgb_learning_rate': 0.030609017491637698, 'xgb_subsample': 0.9623008048869822, 'xgb_colsample_bytree': 0.45007919977699284, 'xgb_gamma': 2.7421351154420126, 'xgb_reg_alpha': 2.3046693658480447e-05, 'xgb_reg_lambda': 1.1516763871878148e-08, 'xgb_scale_pos_weight': 1.8895400008745522}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:25,217] Trial 29 pruned.
[I 2026-06-18 05:51:25,526] Trial 30 finished with value: 0.6968297495236146 and parameters: {'scaler': 'minmax', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 987, 'xgb_learning_rate': 0.027280855946340183, 'xgb_subsample': 0.9474753056820282, 'xgb_colsample_bytree': 0.4798090832508311, 'xgb_gamma': 3.0738056438205215, 'xgb_reg_alpha': 4.3962802352774563e-07, 'xgb_reg_lambda': 5.998047310963351e-07, 'xgb_scale_pos_weight': 1.7073207729702526}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:25,837] Trial 31 pruned.
[I 2026-06-18 05:51:26,146] Trial 32 pruned.
[I 2026-06-18 05:51:26,458] Trial 33 finished with value: 0.6968095555284815 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1011, 'xgb_learning_rate': 0.031224493907600823, 'xgb_subsample': 0.9620455206550734, 'xgb_colsample_bytree': 0.48316712156981045, 'xgb_gamma': 2.779277995722309, 'xgb_reg_alpha': 6.425418202576579e-06, 'xgb_reg_lambda': 3.0172079289190315e-09, 'xgb_scale_pos_weight': 1.8194577738505253}. Best is trial 13 with value: 0.697981567750783.
[I 2026-06-18 05:51:26,781] Trial 34 finished with value: 0.6984784549695845 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1156, 'xgb_learning_rate': 0.0294425759625736, 'xgb_subsample': 0.9685352140687106, 'xgb_colsample_bytree': 0.46609108414683764, 'xgb_gamma': 3.2801037042599455, 'xgb_reg_alpha': 1.0449757458749568e-06, 'xgb_reg_lambda': 4.669131810669013e-07, 'xgb_scale_pos_weight': 1.9411776671579646}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:27,111] Trial 35 finished with value: 0.6971705367960628 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1220, 'xgb_learning_rate': 0.029326422848416682, 'xgb_subsample': 0.9752297583835501, 'xgb_colsample_bytree': 0.46692699468799126, 'xgb_gamma': 3.3068410013581957, 'xgb_reg_alpha': 3.0924159195884356e-07, 'xgb_reg_lambda': 6.398520247761041e-07, 'xgb_scale_pos_weight': 2.022156016679262}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:28,077] Trial 36 pruned.
[I 2026-06-18 05:51:28,391] Trial 37 finished with value: 0.6980572572631724 and parameters: {'scaler': 'robust', 'encoder': 'no_drop', 'model': 'xgb', 'xgb_n_estimators': 1141, 'xgb_learning_rate': 0.03037448015405731, 'xgb_subsample': 0.9666290775323024, 'xgb_colsample_bytree': 0.45937145219337117, 'xgb_gamma': 3.310553863001218, 'xgb_reg_alpha': 9.377845090901934e-07, 'xgb_reg_lambda': 7.785674332374787e-07, 'xgb_scale_pos_weight': 1.8679774746648166}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:28,732] Trial 38 finished with value: 0.6972359768243288 and parameters: {'scaler': 'robust', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1311, 'xgb_learning_rate': 0.029459767651018914, 'xgb_subsample': 0.9673636904669026, 'xgb_colsample_bytree': 0.4587637050680967, 'xgb_gamma': 3.3471150814190387, 'xgb_reg_alpha': 6.670413599969963e-07, 'xgb_reg_lambda': 5.201038784081312e-07, 'xgb_scale_pos_weight': 1.9482048807633807}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:29,675] Trial 39 pruned.
[I 2026-06-18 05:51:30,001] Trial 40 finished with value: 0.6981370804955741 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1170, 'xgb_learning_rate': 0.027117625130713297, 'xgb_subsample': 0.962623621026446, 'xgb_colsample_bytree': 0.4656418386131348, 'xgb_gamma': 3.2193218303308684, 'xgb_reg_alpha': 4.331898571335649e-06, 'xgb_reg_lambda': 1.5642397864586665e-06, 'xgb_scale_pos_weight': 1.8149728349881913}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:30,330] Trial 41 finished with value: 0.6978262709216929 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1159, 'xgb_learning_rate': 0.026668732049380334, 'xgb_subsample': 0.9625891658088421, 'xgb_colsample_bytree': 0.4638411117611799, 'xgb_gamma': 3.2291145013788154, 'xgb_reg_alpha': 3.7949621449250277e-06, 'xgb_reg_lambda': 1.7316621412596968e-06, 'xgb_scale_pos_weight': 1.8139096433274091}. Best is trial 34 with value: 0.6984784549695845.
[I 2026-06-18 05:51:30,656] Trial 42 finished with value: 0.6984927846692416 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1150, 'xgb_learning_rate': 0.026556391586552448, 'xgb_subsample': 0.9625489269371303, 'xgb_colsample_bytree': 0.4640382615161912, 'xgb_gamma': 3.2761028269264987, 'xgb_reg_alpha': 4.045581602288693e-06, 'xgb_reg_lambda': 1.5891802507822228e-06, 'xgb_scale_pos_weight': 1.7994516532658982}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:30,983] Trial 43 finished with value: 0.6977639169543727 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1236, 'xgb_learning_rate': 0.02820780177966552, 'xgb_subsample': 0.9683412048467425, 'xgb_colsample_bytree': 0.46741144377478605, 'xgb_gamma': 3.3736919558993534, 'xgb_reg_alpha': 1.9046247927779066e-05, 'xgb_reg_lambda': 1.291147823154415e-06, 'xgb_scale_pos_weight': 1.7104309051263158}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:31,303] Trial 44 finished with value: 0.696816493511257 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1169, 'xgb_learning_rate': 0.026488301201050547, 'xgb_subsample': 0.9645392562343089, 'xgb_colsample_bytree': 0.4563683897928202, 'xgb_gamma': 3.0456387980016606, 'xgb_reg_alpha': 0.0003742055736756851, 'xgb_reg_lambda': 1.6553083133580514e-05, 'xgb_scale_pos_weight': 1.7406840792895766}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:31,633] Trial 45 finished with value: 0.696791547374345 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1144, 'xgb_learning_rate': 0.027980826738005272, 'xgb_subsample': 0.9604862618927148, 'xgb_colsample_bytree': 0.484423119904945, 'xgb_gamma': 3.2868721275696737, 'xgb_reg_alpha': 4.385267239552504e-05, 'xgb_reg_lambda': 1.606255996965113e-07, 'xgb_scale_pos_weight': 1.818681010082186}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:31,960] Trial 46 finished with value: 0.6977869331820002 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1195, 'xgb_learning_rate': 0.029840392175505784, 'xgb_subsample': 0.9532970389256521, 'xgb_colsample_bytree': 0.4650481722636684, 'xgb_gamma': 3.398003377265537, 'xgb_reg_alpha': 4.323934832304557e-06, 'xgb_reg_lambda': 1.1759918548703798e-05, 'xgb_scale_pos_weight': 1.864925394755357}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:32,268] Trial 47 pruned.
[I 2026-06-18 05:51:32,640] Trial 48 pruned.
[I 2026-06-18 05:51:33,027] Trial 49 pruned.
[I 2026-06-18 05:51:34,028] Trial 50 pruned.
[I 2026-06-18 05:51:34,355] Trial 51 pruned.
[I 2026-06-18 05:51:34,664] Trial 52 pruned.
[I 2026-06-18 05:51:34,996] Trial 53 finished with value: 0.6975332956361016 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1184, 'xgb_learning_rate': 0.026171841675131667, 'xgb_subsample': 0.9662095032525893, 'xgb_colsample_bytree': 0.4683376878694546, 'xgb_gamma': 3.200015002471078, 'xgb_reg_alpha': 1.002250239742262e-05, 'xgb_reg_lambda': 9.86175927938465e-07, 'xgb_scale_pos_weight': 1.863453628442368}. Best is trial 42 with value: 0.6984927846692416.
[I 2026-06-18 05:51:35,334] Trial 54 pruned.
[I 2026-06-18 05:51:35,651] Trial 55 pruned.
[I 2026-06-18 05:51:35,974] Trial 56 finished with value: 0.6978320232497952 and parameters: {'scaler': 'std', 'encoder': 'drop_first', 'model': 'xgb', 'xgb_n_estimators': 1266, 'xgb_learning_rate': 0.030198660792162456, 'xgb_subsample': 0.959313298344265, 'xgb_colsample_bytree': 0.45054901264464087, 'xgb_gamma': 3.395956479998472, 'xgb_reg_alpha': 1.5666310783396248e-07, 'xgb_reg_lambda': 2.4951869461721113e-06, 'xgb_scale_pos_weight': 1.8648021233787968}. Best is trial 42 with value: 0.6984927846692416.

## 4. Display Session Optimization Diagnostics Results

In [9]:
print(f"\nTop Optimization Average Precision Score Target: {study.best_value:.4f}")
print("\nOptimal Parameter Combinations Selected:")
for parameter_key, parameter_value in study.best_params.items():
    print(f" * {parameter_key}: {parameter_value}")

Top Optimization Average Precision Score Target: 0.7011

Optimal Parameter Combinations Selected:
 * scaler: robust
 * encoder: drop_first
 * model: xgb
 * xgb_n_estimators: 1193
 * xgb_learning_rate: 0.02666397513885387
 * xgb_subsample: 0.9405664371553261
 * xgb_colsample_bytree: 0.5071531693840389
 * xgb_gamma: 3.3272862165562556
 * xgb_reg_alpha: 3.5662055338761855e-07
 * xgb_reg_lambda: 1.57208112167439e-08
 * xgb_scale_pos_weight: 1.674451432575116

In [10]:
suggestions = utils.suggest_numeric_ranges(study)
display(suggestions)

,parameter,current_min,current_max,best_median,action,suggested_min,suggested_max
0,xgb_learning_rate,2.500081e-02,0.038387,2.641775e-02,move_left,0.018308,0.038387
1,xgb_reg_alpha,1.034129e-08,0.000976,3.356325e-07,move_left,-0.000488,0.000976
2,xgb_reg_lambda,1.002093e-09,0.000097,1.869154e-08,move_left,-0.000048,0.000097
3,xgb_scale_pos_weight,1.600003e+00,2.093801,1.629352e+00,move_left,1.353103,2.093801
4,xgb_subsample,9.400002e-01,0.979183,9.408030e-01,move_left,0.920409,0.979183
5,xgb_gamma,1.946135e+00,3.499981,3.409834e+00,move_right,1.946135,4.276904
6,xgb_colsample_bytree,4.500792e-01,0.595474,5.143019e-01,narrow,0.499548,0.522617
7,xgb_n_estimators,8.000000e+02,1400.000000,9.840000e+02,narrow,913.240000,1051.560000

In [12]:
runs_df = mlflow.search_runs()
# Select rows where 'tags.mlflow.parentRunId' is missing (meaning it IS a parent/master run)
parent_summary_df = runs_df[runs_df["tags.mlflow.parentRunId"].isna() & (runs_df["status"] == "FINISHED")]

# Isolate evaluation metrics
metric_cols = [c for c in parent_summary_df.columns if c.startswith("metrics.")]
display(parent_summary_df[["start_time"] + metric_cols])

,start_time,metrics.pr_auc,metrics.test_recall,metrics.train_f1,metrics.train_pr_auc,metrics.test_accuracy,metrics.train_roc_auc,metrics.best_auc,metrics.test_pr_auc,metrics.test_f1,metrics.train_recall,metrics.test_roc_auc,metrics.train_precision,metrics.test_precision,metrics.train_accuracy
5000,2026-06-18 11:51:05.297000+00:00,NaN,0.598039,0.719371,0.833148,0.8650,0.940743,0.701076,0.736358,0.643799,0.666411,0.876276,0.781475,0.697143,0.894062
5011,2026-06-18 11:28:51.412000+00:00,NaN,0.583333,0.740313,0.849821,0.8625,0.948050,0.696080,0.733325,0.633822,0.688650,0.874386,0.800357,0.693878,0.901563
5022,2026-06-18 11:24:36.134000+00:00,NaN,0.583333,0.740313,0.849821,0.8625,0.948050,0.696080,0.733325,0.633822,0.688650,0.874386,0.800357,0.693878,0.901563

In [13]:
run_id = parent_summary_df.iloc[0]["run_id"]

run = mlflow.get_run(run_id)

print(run.data.metrics)

{'best_auc': 0.7010758060322027, 'train_accuracy': 0.8940625, 'train_precision': 0.7814748201438849, 'train_recall': 0.6664110429447853, 'train_f1': 0.7193708609271523, 'train_roc_auc': 0.9407429500823452, 'train_pr_auc': 0.8331477466491667, 'test_accuracy': 0.865, 'test_precision': 0.6971428571428572, 'test_recall': 0.5980392156862745, 'test_f1': 0.6437994722955145, 'test_roc_auc': 0.8762762956941571, 'test_pr_auc': 0.736357614669004}

In [14]:
parent_summary_df

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.pr_auc,metrics.test_recall,metrics.train_f1,metrics.train_pr_auc,...,tags.xgb_colsample_bytree_distribution,tags.model_distribution,tags.xgb_learning_rate_distribution,tags.xgb_subsample_distribution,tags.encoder_distribution,tags.xgb_gamma_distribution,tags.rf_max_depth_distribution,tags.rf_n_estimators_distribution,tags.rf_min_samples_leaf_distribution,tags.rf_min_samples_split_distribution
5000,525c024b77e645028f4616c00f34b044,1,FINISHED,file:///Users/hector.vargas/repos/ml_hands_on_...,2026-06-18 11:51:05.297000+00:00,2026-06-18 12:57:00.865000+00:00,NaN,0.598039,0.719371,0.833148,...,None,None,None,None,None,None,None,None,None,None
5011,5f2fd1dc86194a0f89a9555b199fa9cf,1,FINISHED,file:///Users/hector.vargas/repos/ml_hands_on_...,2026-06-18 11:28:51.412000+00:00,2026-06-18 11:29:09.127000+00:00,NaN,0.583333,0.740313,0.849821,...,None,None,None,None,None,None,None,None,None,None
5022,912ffa2b5d69402e85318243adf7ce03,1,FINISHED,file:///Users/hector.vargas/repos/ml_hands_on_...,2026-06-18 11:24:36.134000+00:00,2026-06-18 11:24:53.337000+00:00,NaN,0.583333,0.740313,0.849821,...,None,None,None,None,None,None,None,None,None,None

In [ ]:
# from src import feature_engineering as fe
# fe.remove_recent_runs(EXPERIMENT_NAME, 100000)

In [17]:
rf_runs = (
    parent_summary_df[parent_summary_df["params.model"] == "rf"]
    .sort_values(
        "metrics.train_pr_auc",
        ascending=False
    )
)

rf_runs[
    [
        "run_id",
        'metrics.train_pr_auc',
        "metrics.pr_auc",
        "params.rf_max_depth",
        "params.rf_n_estimators",
        "params.rf_min_samples_split",
        "params.rf_min_samples_leaf",
    ]
]

Empty DataFrame
Columns: [run_id, metrics.train_pr_auc, metrics.pr_auc, params.rf_max_depth, params.rf_n_estimators, params.rf_min_samples_split, params.rf_min_samples_leaf]
Index: []

In [ ]:
xgb_runs = (
    parent_summary_df[parent_summary_df["params.model"] == "xgb"]
    .sort_values(
        "metrics.train_pr_auc",
        ascending=False
    )
)

xgb_runs[
    [
        "run_id",
        "metrics.train_pr_auc",
        "metrics.test_pr_auc",
        "metrics.pr_auc",
        "params.xgb_n_estimators",
        "params.xgb_learning_rate",
        "params.xgb_gamma",
        "params.xgb_scale_pos_weight",
    ]
].head(20)

,run_id,metrics.train_pr_auc,metrics.test_pr_auc,metrics.pr_auc,params.xgb_n_estimators,params.xgb_learning_rate,params.xgb_gamma,params.xgb_scale_pos_weight
5011,5f2fd1dc86194a0f89a9555b199fa9cf,0.849821,0.733325,NaN,1264,0.02809743391955222,2.9137146876952342,1.6370223258670453
5022,912ffa2b5d69402e85318243adf7ce03,0.849821,0.733325,NaN,1264,0.02809743391955222,2.9137146876952342,1.6370223258670453
5000,525c024b77e645028f4616c00f34b044,0.833148,0.736358,NaN,1193,0.02666397513885387,3.3272862165562556,1.674451432575116